version: '3'

services: 
  chat-flask-server:
    image: chat-flask-base
    container_name: "chat-flask"
    build: .
    hostname: "chat-flask"
    volumes:
      - ./flask_web_server:/var/www/flask_web_server
    ports:
      - 5000:5000
    working_dir : /var/www/flask_web_server
    command: ["sh", "docker-entrypoint.sh"]
    environment:
      - APPENV=DEV
    depends_on:
      - "chat-mongo"
      - "chat-redis"

  # nuxt-front-app:
  #   image: node:11.13.0-alpine
  #   container_name: "nuxt-front-app"
  #   build: 
  #     context: ./nuxt-app
  #     dockerfile: ./nuxt-app/Dockerfile
  #   working_dir: "/usr/local/src/nuxt-app"
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - ./nuxt-app:/usr/local/src/nuxt-app
  #   environment:
  #     - HOST=0.0.0.0
  #   command: npm run dev
    # command: /bin/sh -c "npm install && npm run dev"    

  chat-redis:
    image: redis
    container_name: "chat-redis"
    hostname: "chat-redis"
    volumes:
      - ./redis-data/:/usr/local/etc/redis/
    ports:
      - 6379:6379
    working_dir : /usr/local/etc/redis
    command: ["sh", "/usr/local/etc/redis/docker-entrypoint.sh"]

  chat-mongo:
    image: mongo:3.4
    container_name: "chat-mongo"
    hostname: "chat-mongo"
    ports:
      - 27017:27017