version: '3'

services: 
  chat-flask-server:
    image: chat-flask-base
    container_name: "chat-flask"
    build: .
    hostname: "chat-flask"
    volumes:
      - ./flask_web_server:/var/www/flask_web_server
    ports:
      - 5000:5000
    working_dir : /var/www/flask_web_server
    command: ["sh", "docker-entrypoint.sh"]
    depends_on:
      - "chat-mongo"
      - "chat-redis"

  chat-redis:
    image: redis
    container_name: "chat-redis"
    hostname: "chat-redis"
    volumes:
      - ./redis-data/:/usr/local/etc/redis/
    ports:
      - 6379:6379
    working_dir : /usr/local/etc/redis
    command: ["sh", "/usr/local/etc/redis/docker-entrypoint.sh"]

  chat-mongo:
    image: mongo:3.4
    container_name: "chat-mongo"
    hostname: "chat-mongo"
    ports:
      - 27017:27017